Remove !defined(__m68k__) guard when compiling for Atari TOS
A stray #include "atari/psg.h" in system/atari/psg.c was the cause. Fixes:

m68k-linux-gnu-gcc -g -O2 -Werror=implicit-function-declaration -ffile-prefix-map=/build/reproducible-path/ocp-3.4.0+ds=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -Wall -fPIC -I.././ psgplay-git/lib/m68k/m68kcpu.c -o m68k_m68kcpu.o -c -Ipsgplay-git/include -Ipsgplay-git/lib/cf68901/include -Ipsgplay-git/lib/cf2149/include -Ipsgplay-git/lib/cf300588/include
In file included from psgplay-git/lib/m68k/m68kcpu.c:16:
psgplay-git/lib/m68k/m68kcpu.c: In function ‘m68k_execute’:
psgplay-git/include/m68k/m68kcpu.h:1908:38: error: implicit declaration of function ‘setjmp’ [-Wimplicit-function-declaration]
 1908 | #define m68ki_check_bus_error_trap() setjmp(module->m68ki_bus_error_jmp_buf)
      |                                      ^~~~~~
psgplay-git/lib/m68k/m68kcpu.c:902:17: note: in expansion of macro ‘m68ki_check_bus_error_trap’
  902 |                 m68ki_check_bus_error_trap();
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
psgplay-git/include/m68k/m68kcpu.h:1908:51: error: ‘struct m68k_module’ has no member named ‘m68ki_bus_error_jmp_buf’
 1908 | #define m68ki_check_bus_error_trap() setjmp(module->m68ki_bus_error_jmp_buf)
      |                                                   ^~
psgplay-git/lib/m68k/m68kcpu.c:902:17: note: in expansion of macro ‘m68ki_check_bus_error_trap’
  902 |                 m68ki_check_bus_error_trap();
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~